// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/revenue/v1/events.proto (package evmos.revenue.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * EventRegisterRevenue is an event emitted when a contract is registered to receive a percentage of tx fees.
 *
 * @generated from message evmos.revenue.v1.EventRegisterRevenue
 */
export const EventRegisterRevenue = proto3.makeMessageType(
  "evmos.revenue.v1.EventRegisterRevenue",
  () => [
    { no: 1, name: "deployer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "effective_withdrawer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventUpdateRevenue is an event emitted when a withdrawer address is updated for a contract.
 *
 * @generated from message evmos.revenue.v1.EventUpdateRevenue
 */
export const EventUpdateRevenue = proto3.makeMessageType(
  "evmos.revenue.v1.EventUpdateRevenue",
  () => [
    { no: 1, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "deployer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "withdrawer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventCancelRevenue is an event emitted when a contract is unregistered from receiving tx fees.
 *
 * @generated from message evmos.revenue.v1.EventCancelRevenue
 */
export const EventCancelRevenue = proto3.makeMessageType(
  "evmos.revenue.v1.EventCancelRevenue",
  () => [
    { no: 1, name: "deployer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventDistributeRevenue is an event emitted when a contract receives a percentage of tx fees.
 *
 * @generated from message evmos.revenue.v1.EventDistributeRevenue
 */
export const EventDistributeRevenue = proto3.makeMessageType(
  "evmos.revenue.v1.EventDistributeRevenue",
  () => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "withdrawer_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

