// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/revenue/v1/revenue.proto (package evmos.revenue.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Revenue defines an instance that organizes fee distribution conditions for
 * the owner of a given smart contract
 *
 * @generated from message evmos.revenue.v1.Revenue
 */
export declare class Revenue extends Message<Revenue> {
  /**
   * contract_address is the hex address of a registered contract
   *
   * @generated from field: string contract_address = 1;
   */
  contractAddress: string;

  /**
   * deployer_address is the bech32 address of message sender. It must be the same as the origin EOA
   * sending the transaction which deploys the contract
   *
   * @generated from field: string deployer_address = 2;
   */
  deployerAddress: string;

  /**
   * withdrawer_address is the bech32 address of account receiving the transaction fees it defaults to
   * deployer_address
   *
   * @generated from field: string withdrawer_address = 3;
   */
  withdrawerAddress: string;

  constructor(data?: PartialMessage<Revenue>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "evmos.revenue.v1.Revenue";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Revenue;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Revenue;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Revenue;

  static equals(a: Revenue | PlainMessage<Revenue> | undefined, b: Revenue | PlainMessage<Revenue> | undefined): boolean;
}

