// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/vesting/v1/events.proto (package evmos.vesting.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * EventCreateClawbackVestingAccount defines the event type
 * for creating a clawback vesting account
 *
 * @generated from message evmos.vesting.v1.EventCreateClawbackVestingAccount
 */
export const EventCreateClawbackVestingAccount = proto3.makeMessageType(
  "evmos.vesting.v1.EventCreateClawbackVestingAccount",
  () => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "coins", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "start_time", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "merge", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventClawback defines the event type for clawback
 *
 * @generated from message evmos.vesting.v1.EventClawback
 */
export const EventClawback = proto3.makeMessageType(
  "evmos.vesting.v1.EventClawback",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "destination", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventUpdateVestingFunder defines the event type for updating the vesting funder
 *
 * @generated from message evmos.vesting.v1.EventUpdateVestingFunder
 */
export const EventUpdateVestingFunder = proto3.makeMessageType(
  "evmos.vesting.v1.EventUpdateVestingFunder",
  () => [
    { no: 1, name: "funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "new_funder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

