// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/vesting/v1/query.proto (package evmos.vesting.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Coin } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/base/v1beta1/coin_pb.js";

/**
 * QueryBalancesRequest is the request type for the Query/Balances RPC method.
 *
 * @generated from message evmos.vesting.v1.QueryBalancesRequest
 */
export const QueryBalancesRequest = proto3.makeMessageType(
  "evmos.vesting.v1.QueryBalancesRequest",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * QueryBalancesResponse is the response type for the Query/Balances RPC
 * method.
 *
 * @generated from message evmos.vesting.v1.QueryBalancesResponse
 */
export const QueryBalancesResponse = proto3.makeMessageType(
  "evmos.vesting.v1.QueryBalancesResponse",
  () => [
    { no: 1, name: "locked", kind: "message", T: Coin, repeated: true },
    { no: 2, name: "unvested", kind: "message", T: Coin, repeated: true },
    { no: 3, name: "vested", kind: "message", T: Coin, repeated: true },
  ],
);

