// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/incentives/v1/incentives.proto (package evmos.incentives.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { DecCoin } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/base/v1beta1/coin_pb.js";

/**
 * Incentive defines an instance that organizes distribution conditions for a
 * given smart contract
 *
 * @generated from message evmos.incentives.v1.Incentive
 */
export const Incentive = proto3.makeMessageType(
  "evmos.incentives.v1.Incentive",
  () => [
    { no: 1, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "allocations", kind: "message", T: DecCoin, repeated: true },
    { no: 3, name: "epochs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "start_time", kind: "message", T: Timestamp },
    { no: 5, name: "total_gas", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * GasMeter tracks the cumulative gas spent per participant in one epoch
 *
 * @generated from message evmos.incentives.v1.GasMeter
 */
export const GasMeter = proto3.makeMessageType(
  "evmos.incentives.v1.GasMeter",
  () => [
    { no: 1, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "participant", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cumulative_gas", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * RegisterIncentiveProposal is a gov Content type to register an incentive
 *
 * @generated from message evmos.incentives.v1.RegisterIncentiveProposal
 */
export const RegisterIncentiveProposal = proto3.makeMessageType(
  "evmos.incentives.v1.RegisterIncentiveProposal",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "allocations", kind: "message", T: DecCoin, repeated: true },
    { no: 5, name: "epochs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * CancelIncentiveProposal is a gov Content type to cancel an incentive
 *
 * @generated from message evmos.incentives.v1.CancelIncentiveProposal
 */
export const CancelIncentiveProposal = proto3.makeMessageType(
  "evmos.incentives.v1.CancelIncentiveProposal",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

