// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/inflation/v1/genesis.proto (package evmos.inflation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { ExponentialCalculation, InflationDistribution } from "./inflation_pb.js";

/**
 * GenesisState defines the inflation module's genesis state.
 *
 * @generated from message evmos.inflation.v1.GenesisState
 */
export const GenesisState = proto3.makeMessageType(
  "evmos.inflation.v1.GenesisState",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "period", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "epoch_identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "epochs_per_period", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "skipped_epochs", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * Params holds parameters for the inflation module.
 *
 * @generated from message evmos.inflation.v1.Params
 */
export const Params = proto3.makeMessageType(
  "evmos.inflation.v1.Params",
  () => [
    { no: 1, name: "mint_denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "exponential_calculation", kind: "message", T: ExponentialCalculation },
    { no: 3, name: "inflation_distribution", kind: "message", T: InflationDistribution },
    { no: 4, name: "enable_inflation", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

