// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/erc20/v1/events.proto (package evmos.erc20.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * EventRegisterPair is an event emitted when a coin is registered.
 *
 * @generated from message evmos.erc20.v1.EventRegisterPair
 */
export const EventRegisterPair = proto3.makeMessageType(
  "evmos.erc20.v1.EventRegisterPair",
  () => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "erc20_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventToggleTokenConversion is an event emitted when a coin's token conversion is toggled.
 *
 * @generated from message evmos.erc20.v1.EventToggleTokenConversion
 */
export const EventToggleTokenConversion = proto3.makeMessageType(
  "evmos.erc20.v1.EventToggleTokenConversion",
  () => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "erc20_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventConvertCoin is an event emitted when a coin is converted.
 *
 * @generated from message evmos.erc20.v1.EventConvertCoin
 */
export const EventConvertCoin = proto3.makeMessageType(
  "evmos.erc20.v1.EventConvertCoin",
  () => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "erc20_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * EventConvertERC20 is an event emitted when an ERC20 is converted.
 *
 * @generated from message evmos.erc20.v1.EventConvertERC20
 */
export const EventConvertERC20 = proto3.makeMessageType(
  "evmos.erc20.v1.EventConvertERC20",
  () => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

