// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/claims/v1/claims.proto (package evmos.claims.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Action defines the list of available actions to claim the airdrop tokens.
 *
 * @generated from enum evmos.claims.v1.Action
 */
export const Action = proto3.makeEnum(
  "evmos.claims.v1.Action",
  [
    {no: 0, name: "ACTION_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "ACTION_VOTE", localName: "VOTE"},
    {no: 2, name: "ACTION_DELEGATE", localName: "DELEGATE"},
    {no: 3, name: "ACTION_EVM", localName: "EVM"},
    {no: 4, name: "ACTION_IBC_TRANSFER", localName: "IBC_TRANSFER"},
  ],
);

/**
 * Claim defines the action, completed flag and the remaining claimable amount
 * for a given user. This is only used during client queries.
 *
 * @generated from message evmos.claims.v1.Claim
 */
export const Claim = proto3.makeMessageType(
  "evmos.claims.v1.Claim",
  () => [
    { no: 1, name: "action", kind: "enum", T: proto3.getEnumType(Action) },
    { no: 2, name: "completed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "claimable_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ClaimsRecordAddress is the claims metadata per address that is used at
 * Genesis.
 *
 * @generated from message evmos.claims.v1.ClaimsRecordAddress
 */
export const ClaimsRecordAddress = proto3.makeMessageType(
  "evmos.claims.v1.ClaimsRecordAddress",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "initial_claimable_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "actions_completed", kind: "scalar", T: 8 /* ScalarType.BOOL */, repeated: true },
  ],
);

/**
 * ClaimsRecord defines the initial claimable airdrop amount and the list of
 * completed actions to claim the tokens.
 *
 * @generated from message evmos.claims.v1.ClaimsRecord
 */
export const ClaimsRecord = proto3.makeMessageType(
  "evmos.claims.v1.ClaimsRecord",
  () => [
    { no: 1, name: "initial_claimable_amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actions_completed", kind: "scalar", T: 8 /* ScalarType.BOOL */, repeated: true },
  ],
);

