// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/claims/v1/genesis.proto (package evmos.claims.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3, Timestamp } from "@bufbuild/protobuf";
import { ClaimsRecordAddress } from "./claims_pb.js";

/**
 * GenesisState define the claims module's genesis state.
 *
 * @generated from message evmos.claims.v1.GenesisState
 */
export const GenesisState = proto3.makeMessageType(
  "evmos.claims.v1.GenesisState",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "claims_records", kind: "message", T: ClaimsRecordAddress, repeated: true },
  ],
);

/**
 * Params defines the claims module's parameters.
 *
 * @generated from message evmos.claims.v1.Params
 */
export const Params = proto3.makeMessageType(
  "evmos.claims.v1.Params",
  () => [
    { no: 1, name: "enable_claims", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "airdrop_start_time", kind: "message", T: Timestamp },
    { no: 3, name: "duration_until_decay", kind: "message", T: Duration },
    { no: 4, name: "duration_of_decay", kind: "message", T: Duration },
    { no: 5, name: "claims_denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "authorized_channels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "evm_channels", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

