// @generated by protoc-gen-es v1.0.0 with parameter "rewrite_imports=./google/api/**/*_pb.js:@buf/googleapis_googleapis.bufbuild_es,rewrite_imports=./gogoproto/**/*_pb.js:@buf/cosmos_gogo-proto.bufbuild_es,rewrite_imports=./cosmos_proto/**/*_pb.js:@buf/cosmos_cosmos-proto.bufbuild_es,rewrite_imports=./cosmos/vesting/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/msg/v1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/base/query/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/bank/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./cosmos/auth/v1beta1/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es,rewrite_imports=./amino/**/*_pb.js:@buf/cosmos_cosmos-sdk.bufbuild_es"
// @generated from file evmos/epochs/v1/query.proto (package evmos.epochs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { PageRequest, PageResponse } from "@buf/cosmos_cosmos-sdk.bufbuild_es/cosmos/base/query/v1beta1/pagination_pb.js";
import { EpochInfo } from "./genesis_pb.js";

/**
 * QueryEpochsInfoRequest is the request type for the Query/EpochInfos RPC
 * method.
 *
 * @generated from message evmos.epochs.v1.QueryEpochsInfoRequest
 */
export const QueryEpochsInfoRequest = proto3.makeMessageType(
  "evmos.epochs.v1.QueryEpochsInfoRequest",
  () => [
    { no: 1, name: "pagination", kind: "message", T: PageRequest },
  ],
);

/**
 * QueryEpochsInfoResponse is the response type for the Query/EpochInfos RPC
 * method.
 *
 * @generated from message evmos.epochs.v1.QueryEpochsInfoResponse
 */
export const QueryEpochsInfoResponse = proto3.makeMessageType(
  "evmos.epochs.v1.QueryEpochsInfoResponse",
  () => [
    { no: 1, name: "epochs", kind: "message", T: EpochInfo, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ],
);

/**
 * QueryCurrentEpochRequest is the request type for the Query/EpochInfos RPC
 * method.
 *
 * @generated from message evmos.epochs.v1.QueryCurrentEpochRequest
 */
export const QueryCurrentEpochRequest = proto3.makeMessageType(
  "evmos.epochs.v1.QueryCurrentEpochRequest",
  () => [
    { no: 1, name: "identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * QueryCurrentEpochResponse is the response type for the Query/EpochInfos RPC
 * method.
 *
 * @generated from message evmos.epochs.v1.QueryCurrentEpochResponse
 */
export const QueryCurrentEpochResponse = proto3.makeMessageType(
  "evmos.epochs.v1.QueryCurrentEpochResponse",
  () => [
    { no: 1, name: "current_epoch", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

